services:

  mariadb:
    container_name: mariadb_scee
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: scee123
      MYSQL_DATABASE: SCEE
      MYSQL_USER: scee_user
      MYSQL_PASSWORD: scee_pass

    ports:
      - 13306:3306

    volumes:
      - ~/apps/mariadb_scee/data:/var/lib/mysql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# To run this docker-compose file, save it as 'compose.yaml' and execute:
# docker-compose -f compose.yaml up -d
# You can then access Adminer at http://localhost:8080
# Use the following credentials to log in:
# System: MySQL
# Server: db
# Username: root
# Password: scee123
# https://hub.docker.com/_/mariadb